# Generated by Django 6.0.6 on 2026-07-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_code', models.CharField(max_length=10, unique=True)),
                ('crop_name', models.CharField(max_length=100)),
            ],
        ),
    ]
