# Generated by Django 6.0.6 on 2026-07-10 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_code', models.CharField(max_length=2, unique=True)),
                ('crop_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CropSubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgroup_code', models.CharField(max_length=6, unique=True)),
                ('subgroup_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.crop')),
            ],
        ),
    ]
