# Generated by Django 6.0.6 on 2026-07-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='crop_code',
        ),
        migrations.AddField(
            model_name='crop',
            name='crop_group_code',
            field=models.CharField(default='gn', max_length=2),
            preserve_default=False,
        ),
    ]
