# Generated by Django 6.0.6 on 2026-07-10 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_remove_crop_crop_code_crop_crop_group_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety_code', models.CharField(max_length=20, unique=True)),
                ('variety_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('subgroup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.cropsubgroup')),
            ],
        ),
    ]
