# Generated by Django 6.0.6 on 2026-07-10 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_variety'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='crop_group_code',
            new_name='crop_code',
        ),
    ]
