# Generated by Django 6.0.6 on 2026-07-10 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_rename_crop_group_code_crop_crop_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growing_group_code', models.CharField(max_length=2)),
                ('growing_group_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='variety',
            name='variety_code',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AddField(
            model_name='variety',
            name='growing_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.growinggroup'),
        ),
    ]
