# Generated by Django 6.0.6 on 2026-07-10 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_growinggroup_alter_variety_variety_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variety',
            name='growing_group',
            field=models.ForeignKey(
    on_delete=django.db.models.deletion.PROTECT,
    to='masterdata.growinggroup'
),
        ),
    ]
