# Generated by Django 6.0.6 on 2026-07-10 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0007_greenhouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenhouse',
            name='greenhouse_name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='GreenhouseBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('LEFT', 'Left'), ('RIGHT', 'Right'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], max_length=5)),
                ('bed_no', models.IntegerField()),
                ('valve', models.IntegerField()),
                ('bay_no', models.IntegerField()),
                ('mother_plants', models.IntegerField()),
                ('control_valve', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.greenhouse')),
            ],
            options={
                'unique_together': {('greenhouse', 'bed_no')},
            },
        ),
    ]
