# Generated by Django 6.0.6 on 2026-07-10 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0008_alter_greenhouse_greenhouse_name_greenhousebed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='greenhousebed',
            unique_together=set(),
        ),
    ]
