# Generated by Django 6.0.6 on 2026-07-11 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0009_alter_greenhousebed_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_reference', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('quantity', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('IN_PRODUCTION', 'In Production'), ('OUT_OF_PRODUCTION', 'Out Of Production')], default='IN_PRODUCTION', max_length=20)),
                ('manual_override', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('greenhouse_bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.greenhousebed')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.variety')),
            ],
        ),
    ]
