# Generated by Django 6.0.6 on 2026-07-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0010_productionallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='growinggroup',
            name='edge_placement_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='growinggroup',
            name='sensitivity_level',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('HIGH', 'High'), ('VERY_HIGH', 'Very High')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='growinggroup',
            name='water_requirement',
            field=models.CharField(blank=True, choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='growinggroup',
            name='growing_group_code',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='greenhousebed',
            unique_together={('greenhouse', 'side', 'bed_no')},
        ),
    ]
