# Generated by Django 6.0.6 on 2026-07-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0011_growinggroup_edge_placement_allowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='growinggroup',
            name='color_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
