# Generated by Django 6.0.6 on 2026-07-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0012_growinggroup_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhouse',
            name='edge_zone_beds',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
