# Generated by Django 6.0.6 on 2026-07-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0013_greenhouse_edge_zone_beds'),
    ]

    operations = [
        migrations.AddField(
            model_name='growinggroup',
            name='placement_preference',
            field=models.CharField(blank=True, choices=[('PREFER_EDGE', 'Prefer Edge'), ('EDGE_ALLOWED', 'Edge Allowed'), ('AVOID_EDGE', 'Avoid Edge')], max_length=20, null=True),
        ),
    ]
