# Generated by Django 6.0.7 on 2026-07-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0014_growinggroup_placement_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='variety',
            name='default_buffer_percent',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='variety',
            name='default_urc_per_bag',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='variety',
            name='rooting_risk_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20),
        ),
    ]
