# Generated by Django 6.0.6 on 2026-07-12 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_reference', models.CharField(max_length=50, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VALIDATED', 'Validated'), ('IMPORTED', 'Imported'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportedStickingPlanRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('variety_code', models.CharField(max_length=20)),
                ('variety_name', models.CharField(blank=True, max_length=255)),
                ('greenhouse_code', models.CharField(max_length=20)),
                ('sticking_week', models.CharField(max_length=10)),
                ('production_end_week', models.CharField(max_length=10)),
                ('planned_quantity', models.IntegerField(default=0)),
                ('urc_per_bag', models.IntegerField(default=0)),
                ('validation_status', models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid')], default='PENDING', max_length=20)),
                ('validation_message', models.TextField(blank=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='planning.importbatch')),
            ],
        ),
    ]
