# Generated by Django 6.0.7 on 2026-07-14 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0014_growinggroup_placement_preference'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StickingPlanHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('season', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('ALLOCATED', 'Allocated'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.importbatch')),
            ],
        ),
        migrations.CreateModel(
            name='StickingPlanLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sticking_week', models.CharField(max_length=10)),
                ('planting_week', models.CharField(blank=True, max_length=10)),
                ('planting_week_override', models.BooleanField(default=False)),
                ('production_end_week', models.CharField(max_length=10)),
                ('planned_quantity', models.IntegerField()),
                ('buffer_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('urc_per_bag', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ALLOCATED', 'Allocated'), ('PRODUCED', 'Produced')], default='PLANNED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.greenhouse')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='planning.stickingplanheader')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.variety')),
            ],
        ),
    ]
