# Generated by Django 6.0.7 on 2026-07-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_stickingplanheader_stickingplanline'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickingplanline',
            name='reference',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
