# Generated by Django 6.0.7 on 2026-07-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_stickingplanline_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickingplanheader',
            name='reference',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
