# Generated by Django 6.0.7 on 2026-07-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_alter_stickingplanheader_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='imports/'),
        ),
    ]
