# Generated by Django 6.0.6 on 2026-07-14 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0014_growinggroup_placement_preference'),
        ('planning', '0005_importbatch_uploaded_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_capacity', models.IntegerField()),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PROPOSED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.greenhouse')),
                ('sticking_plan_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_proposals', to='planning.stickingplanline')),
            ],
        ),
    ]
