# Generated by Django 6.0.6 on 2026-07-14 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0014_growinggroup_placement_preference'),
        ('planning', '0006_allocationproposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_allocations', to='planning.allocationproposal')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.greenhousebed')),
            ],
        ),
    ]
