# Generated by Django 6.0.7 on 2026-07-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_bedallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedstickingplanrow',
            name='applied_buffer_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='importedstickingplanrow',
            name='buffer_override_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='importedstickingplanrow',
            name='buffer_source',
            field=models.CharField(choices=[('DEFAULT', 'Default'), ('OVERRIDE', 'Override')], default='DEFAULT', max_length=20),
        ),
        migrations.AddField(
            model_name='importedstickingplanrow',
            name='override_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='importedstickingplanrow',
            name='override_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='importedstickingplanrow',
            name='target_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
