# Generated by Django 6.0.7 on 2026-07-15 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0015_variety_default_buffer_percent_and_more'),
        ('planning', '0008_importedstickingplanrow_applied_buffer_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BufferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sticking_week', models.CharField(max_length=10)),
                ('demand_quantity', models.IntegerField()),
                ('target_quantity', models.IntegerField()),
                ('rooted_quantity', models.IntegerField(default=0)),
                ('loss_quantity', models.IntegerField(default=0)),
                ('loss_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('buffer_used', models.DecimalField(decimal_places=2, max_digits=5)),
                ('buffer_source', models.CharField(default='DEFAULT', max_length=20)),
                ('override_reason', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.greenhouse')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.variety')),
            ],
        ),
    ]
