# Generated by Django 6.0.7 on 2026-07-17 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0015_variety_default_buffer_percent_and_more'),
        ('planning', '0009_bufferhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allocationproposal',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='bedallocation',
            options={'ordering': ['bed']},
        ),
        migrations.AlterModelOptions(
            name='bufferhistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='importbatch',
            options={'ordering': ['-imported_at'], 'verbose_name': 'Import Batch', 'verbose_name_plural': 'Import Batches'},
        ),
        migrations.AlterModelOptions(
            name='importedstickingplanrow',
            options={'ordering': ['row_number']},
        ),
        migrations.AlterModelOptions(
            name='stickingplanheader',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sticking Plan Header', 'verbose_name_plural': 'Sticking Plan Headers'},
        ),
        migrations.AlterModelOptions(
            name='stickingplanline',
            options={'ordering': ['sticking_week', 'greenhouse', 'variety']},
        ),
        migrations.AlterField(
            model_name='allocationproposal',
            name='status',
            field=models.CharField(choices=[('PROPOSED', 'Proposed'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], db_index=True, default='PROPOSED', max_length=20),
        ),
        migrations.AlterField(
            model_name='bufferhistory',
            name='sticking_week',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='batch_reference',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VALIDATED', 'Validated'), ('IMPORTED', 'Imported'), ('FAILED', 'Failed')], db_index=True, default='UPLOADED', max_length=20),
        ),
        migrations.AlterField(
            model_name='importedstickingplanrow',
            name='greenhouse_code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='importedstickingplanrow',
            name='sticking_week',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='importedstickingplanrow',
            name='validation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='importedstickingplanrow',
            name='variety_code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='stickingplanheader',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sticking_plans', to='planning.importbatch'),
        ),
        migrations.AlterField(
            model_name='stickingplanheader',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='stickingplanheader',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('ALLOCATED', 'Allocated'), ('COMPLETED', 'Completed')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='stickingplanline',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='stickingplanline',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('ALLOCATED', 'Allocated'), ('PRODUCED', 'Produced')], db_index=True, default='PLANNED', max_length=20),
        ),
        migrations.AlterField(
            model_name='stickingplanline',
            name='sticking_week',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name='allocationproposal',
            index=models.Index(fields=['status'], name='planning_al_status_cdfef6_idx'),
        ),
        migrations.AddIndex(
            model_name='allocationproposal',
            index=models.Index(fields=['greenhouse'], name='planning_al_greenho_3be27e_idx'),
        ),
        migrations.AddIndex(
            model_name='bufferhistory',
            index=models.Index(fields=['sticking_week'], name='planning_bu_stickin_80bb92_idx'),
        ),
        migrations.AddIndex(
            model_name='bufferhistory',
            index=models.Index(fields=['variety'], name='planning_bu_variety_25e8c1_idx'),
        ),
        migrations.AddIndex(
            model_name='bufferhistory',
            index=models.Index(fields=['greenhouse'], name='planning_bu_greenho_45f79d_idx'),
        ),
        migrations.AddIndex(
            model_name='importedstickingplanrow',
            index=models.Index(fields=['variety_code'], name='planning_im_variety_65abea_idx'),
        ),
        migrations.AddIndex(
            model_name='importedstickingplanrow',
            index=models.Index(fields=['greenhouse_code'], name='planning_im_greenho_8467f8_idx'),
        ),
        migrations.AddIndex(
            model_name='importedstickingplanrow',
            index=models.Index(fields=['sticking_week'], name='planning_im_stickin_721ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='importedstickingplanrow',
            index=models.Index(fields=['validation_status'], name='planning_im_validat_b3be8d_idx'),
        ),
        migrations.AddIndex(
            model_name='stickingplanline',
            index=models.Index(fields=['greenhouse'], name='planning_st_greenho_405859_idx'),
        ),
        migrations.AddIndex(
            model_name='stickingplanline',
            index=models.Index(fields=['sticking_week'], name='planning_st_stickin_981fde_idx'),
        ),
        migrations.AddIndex(
            model_name='stickingplanline',
            index=models.Index(fields=['status'], name='planning_st_status_b683e7_idx'),
        ),
    ]
